"""Constants for RFLink Raw Tools."""

DOMAIN = "rflink_raw"
NAME = "RFLink Raw Tools"
VERSION = "0.0.1"
PANEL_BUILD = "neutral-tabs-fix-20260511"
PANEL_URL_PATH = "rflink-raw-tools"
PANEL_TITLE = "RFLink Raw Tools"
PANEL_ICON = "mdi:radio-tower"
STATIC_URL = "/api/rflink_raw/static"
PANEL_MODULE = f"{STATIC_URL}/rflink-raw-tools-panel.js?v={PANEL_BUILD}"
DATA_LAST_RESULT = "last_result"
DATA_LAST_ERROR = "last_error"
DATA_LAST_COMMAND = "last_command"
DATA_LAST_UPDATED = "last_updated"
DATA_DEBUG_RF = "debug_rf"
DATA_DEBUG_QRF = "debug_qrf"
